[[headers]]
  path = "/images/*"
  [headers.values]
    Cache-Control = "max-age=31536000, public"

[[headers]]
  path = "/styles.css"
  [headers.values]
    Cache-Control = "max-age=3600, public"

[[headers]]
  path = "/script.js"
  [headers.values]
    Cache-Control = "max-age=3600, public"